# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ТихоновРоман\answerType0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 470)
        self.numb = QtWidgets.QLabel(Form)
        self.numb.setGeometry(QtCore.QRect(200, 10, 191, 51))
        self.numb.setObjectName("numb")
        self.text = QtWidgets.QLabel(Form)
        self.text.setGeometry(QtCore.QRect(20, 60, 511, 61))
        self.text.setObjectName("text")
        self.next = QtWidgets.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(340, 412, 191, 31))
        self.next.setObjectName("next")
        self.ans = QtWidgets.QLineEdit(Form)
        self.ans.setGeometry(QtCore.QRect(110, 360, 351, 21))
        self.ans.setObjectName("ans")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 350, 61, 41))
        self.label_3.setObjectName("label_3")
        self.im = QtWidgets.QPushButton(Form)
        self.im.setGeometry(QtCore.QRect(410, 310, 141, 31))
        self.im.setObjectName("im")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.numb.setText(_translate("Form", "Вопрос № "))
        self.text.setText(_translate("Form", "Текст вопроса"))
        self.next.setText(_translate("Form", "далее"))
        self.label_3.setText(_translate("Form", "Ответ:"))
        self.im.setText(_translate("Form", "Посмотреть картинку"))


class AnsType0(QWidget, Ui_Form):
    def __init__(self, func):
        self.func = func
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(self.size())
        self.next.clicked.connect(self.close)

    def closeEvent(self, event):
        if self.func:
            self.func()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = AnsType0(None)
    ex.show()
    sys.exit(app.exec_())
