# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ТихоновРоман\answerType12.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 470)
        self.numb = QtWidgets.QLabel(Form)
        self.numb.setGeometry(QtCore.QRect(200, 10, 191, 51))
        self.numb.setObjectName("numb")
        self.text = QtWidgets.QLabel(Form)
        self.text.setGeometry(QtCore.QRect(20, 60, 511, 61))
        self.text.setObjectName("text")
        self.next = QtWidgets.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(340, 412, 191, 31))
        self.next.setObjectName("next")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 291, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.im = QtWidgets.QPushButton(Form)
        self.im.setGeometry(QtCore.QRect(410, 360, 141, 31))
        self.im.setObjectName("im")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.numb.setText(_translate("Form", "Вопрос № "))
        self.text.setText(_translate("Form", "Текст вопроса"))
        self.next.setText(_translate("Form", "далее"))
        self.im.setText(_translate("Form", "посмотреть картинку"))


class AnsType12(QWidget, Ui_Form):
    def __init__(self, func):
        self.func = func
        super().__init__()
        self.setupUi(self)
        self.userAns = {}
        self.setFixedSize(self.size())
        self.next.clicked.connect(self.close)

    def closeEvent(self, event):
        if self.func:
            self.func()

    def button_clicked(self):
        text = self.sender().text()
        self.userAns[text] = (self.userAns[text] + 1) % 2


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = AnsType12(None)
    ex.show()
    sys.exit(app.exec_())
