# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\isser\startEditing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 411)
        self.tests = QtWidgets.QComboBox(Form)
        self.tests.setGeometry(QtCore.QRect(180, 101, 261, 31))
        self.tests.setObjectName("tests")
        self.redact = QtWidgets.QPushButton(Form)
        self.redact.setGeometry(QtCore.QRect(180, 140, 261, 31))
        self.redact.setObjectName("redact")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 110, 81, 16))
        self.label.setObjectName("label")
        self.New = QtWidgets.QPushButton(Form)
        self.New.setGeometry(QtCore.QRect(180, 220, 261, 31))
        self.New.setObjectName("New")
        self.deleteTest = QtWidgets.QPushButton(Form)
        self.deleteTest.setGeometry(QtCore.QRect(180, 180, 261, 31))
        self.deleteTest.setObjectName("deleteTest")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выбрать тест"))
        self.redact.setText(_translate("Form", "Редактировать"))
        self.label.setText(_translate("Form", "Выбрать тест"))
        self.New.setText(_translate("Form", "Создать новый"))
        self.deleteTest.setText(_translate("Form", "Удалить"))


class ChooseTestAndOption(QWidget, Ui_Form):
    def __init__(self, mW):
        super().__init__()
        self.setupUi(self)
        self.mW = mW
        self.setFixedSize(self.size())

    def closeEvent(self, event):
        if self.mW:
            self.mW.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = ChooseTestAndOption(None)
    ex.show()
    sys.exit(app.exec_())
