# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\isser\startTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 411)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(180, 150, 261, 31))
        self.name.setText("")
        self.name.setObjectName("name")
        self.testList = QtWidgets.QComboBox(Form)
        self.testList.setGeometry(QtCore.QRect(180, 101, 261, 31))
        self.testList.setObjectName("testList")
        self.startTest = QtWidgets.QPushButton(Form)
        self.startTest.setGeometry(QtCore.QRect(180, 200, 261, 31))
        self.startTest.setObjectName("startTest")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 110, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 61, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выбрать Тест"))
        self.startTest.setText(_translate("Form", "Начать тестирование"))
        self.label.setText(_translate("Form", "Выбрать тест"))
        self.label_2.setText(_translate("Form", "Ввести имя"))


class ChooseTest(QWidget, Ui_Form):
    def __init__(self, mW):
        super().__init__()
        self.setupUi(self)
        self.mW = mW
        self.setFixedSize(self.size())

    def closeEvent(self, event):
        if self.mW:
            self.mW.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = ChooseTest(None)
    ex.show()
    sys.exit(app.exec_())
