# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.test = QtWidgets.QPushButton(self.centralwidget)
        self.test.setGeometry(QtCore.QRect(180, 110, 271, 31))
        self.test.setObjectName("test")
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(180, 150, 271, 31))
        self.history.setObjectName("history")
        self.redact = QtWidgets.QPushButton(self.centralwidget)
        self.redact.setGeometry(QtCore.QRect(180, 190, 271, 31))
        self.redact.setObjectName("redact")
        self.inf = QtWidgets.QPushButton(self.centralwidget)
        self.inf.setGeometry(QtCore.QRect(590, 291, 31, 31))
        self.inf.setObjectName("inf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TestProgram"))
        self.test.setText(_translate("MainWindow", "Пройти тестирование"))
        self.history.setText(_translate("MainWindow", "История тестирований"))
        self.redact.setText(_translate("MainWindow", "Редактировать тесты"))
        self.inf.setText(_translate("MainWindow", "?"))
